// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srnwteqdthdkrhiundir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNybnd0ZXFkdGhka3JoaXVuZGlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODIzOTcsImV4cCI6MjA2ODk1ODM5N30.kMogjArY2wA76l3TIklX3Fzbmnaot61qGfEs7fwqE3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});